$schema: "1.0"
name: "devbox-customization"
tasks:
  - name: git-clone
    description: 'Clone devcenter examples repository into C:\src'
    parameters:
      repositoryUrl: https://github.com/yachoukh/devcenter-examples.git
      directory: c:\workspaces
  - name: winget
    description: 'Team-based Customizations including: .NET Aspire, Azure Deployment with AZD, Visual Studio 2022 Enterprise'
    parameters:
      configurationFile: 'c:\workspaces\devcenter-examples\devbox-hackathon\winget-configurations\team-personalizations.dsc.yaml'
      runAsUser: true
